# Generated by Django 4.2.30 on 2026-08-21 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SOS_ALERT', 'SOS Emergency Alert'), ('ESCALATION_UPDATE', 'Escalation Stage Update'), ('EMERGENCY_ACCEPTED', 'Emergency Accepted'), ('EMERGENCY_DECLINED', 'Emergency Declined'), ('EMERGENCY_RESOLVED', 'Emergency Resolved'), ('CHAT_MESSAGE', 'New Chat Message'), ('SYSTEM', 'System Notification')], default='SYSTEM', max_length=30)),
                ('stage', models.CharField(blank=True, default='', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='emergency.emergencyincident')),
            ],
            options={
                'db_table': 'careconnect_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
