services:
  - type: web
    name: careconnect-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python seed_data.py
    startCommand: cd backend && gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
