# Generated by Django 4.2.30 on 2026-08-21 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('society', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocietyassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentflatmapping',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_mappings', to='society.flat'),
        ),
        migrations.AddField(
            model_name='residentflatmapping',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flat',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='society.block'),
        ),
        migrations.AddField(
            model_name='block',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='society.society'),
        ),
        migrations.AlterUniqueTogether(
            name='usersocietyassignment',
            unique_together={('user', 'society')},
        ),
        migrations.AlterUniqueTogether(
            name='residentflatmapping',
            unique_together={('resident', 'flat')},
        ),
        migrations.AlterUniqueTogether(
            name='flat',
            unique_together={('block', 'flat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('society', 'name')},
        ),
    ]
