# Generated by Django 4.2.30 on 2026-08-21 13:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SOCIETY_MEMBER', 'Society Members'), ('SECURITY', 'Security Personnel'), ('VOLUNTEER', 'Community Volunteers'), ('ADMIN', 'System Admin'), ('COMPLETED', 'Escalation Completed')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('TIMEOUT', 'Timeout'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'careconnect_emergency_escalation_history',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical Emergency'), ('FIRE', 'Fire Emergency'), ('SECURITY', 'Security Threat'), ('GENERAL', 'General Assistance')], default='GENERAL', max_length=20)),
                ('message', models.TextField(blank=True, default='SOS Alert Triggered!')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('location_address', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ESCALATING', 'Escalating'), ('ACCEPTED', 'Accepted'), ('ACTIVE_RESPONSE', 'Active Response'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled'), ('UNRESPONDED', 'Unresponded')], db_index=True, default='PENDING', max_length=20)),
                ('current_stage', models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SOCIETY_MEMBER', 'Society Members'), ('SECURITY', 'Security Personnel'), ('VOLUNTEER', 'Community Volunteers'), ('ADMIN', 'System Admin'), ('COMPLETED', 'Escalation Completed')], db_index=True, default='PRIMARY_GUARDIAN', max_length=30)),
                ('response_deadline', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('escalation_started_at', models.DateTimeField(auto_now_add=True)),
                ('escalation_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'careconnect_emergency_incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
