# Generated by Django 4.2.30 on 2026-08-21 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyincident',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyincident',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyincident',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyescalation',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_history', to='emergency.emergencyincident'),
        ),
        migrations.AddField(
            model_name='emergencyescalation',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
