# Generated by Django 4.2.30 on 2026-08-26 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergency', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyescalation',
            name='stage',
            field=models.CharField(choices=[('GUARDIAN', 'Guardian'), ('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SOCIETY_MEMBER', 'Society Members'), ('SECURITY', 'Security Personnel'), ('VOLUNTEER', 'Community Volunteers'), ('ADMIN', 'System Admin'), ('COMPLETED', 'Escalation Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencyincident',
            name='current_stage',
            field=models.CharField(choices=[('GUARDIAN', 'Guardian'), ('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SOCIETY_MEMBER', 'Society Members'), ('SECURITY', 'Security Personnel'), ('VOLUNTEER', 'Community Volunteers'), ('ADMIN', 'System Admin'), ('COMPLETED', 'Escalation Completed')], db_index=True, default='GUARDIAN', max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencyincident',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ESCALATING', 'Escalating'), ('RESPONDED', 'Responded'), ('ACCEPTED', 'Accepted'), ('ACTIVE_RESPONSE', 'Active Response'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled'), ('UNRESPONDED', 'Unresponded')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='EmergencyResponder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('guardian_type', models.CharField(choices=[('PRIMARY', 'Primary Guardian'), ('SECONDARY', 'Secondary Guardian'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined'), ('RESPONDING', 'Responding'), ('WITHDRAWN', 'Withdrawn')], default='CONFIRMED', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, default='', max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responders', to='emergency.emergencyincident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'careconnect_emergency_responders',
                'ordering': ['joined_at'],
                'unique_together': {('incident', 'user')},
            },
        ),
    ]
