# Generated by Django 4.2.30 on 2026-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_alter_emergencyescalation_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyincident',
            name='has_requested_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencyescalation',
            name='stage',
            field=models.CharField(choices=[('GUARDIAN', 'Guardian'), ('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SOCIETY_MEMBER', 'Society Members'), ('SECURITY', 'Security Personnel'), ('VOLUNTEER', 'Community Volunteers'), ('ADMIN', 'System Admin'), ('COMMUNITY', 'Community (Society, Security, Volunteers)'), ('COMPLETED', 'Escalation Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencyincident',
            name='current_stage',
            field=models.CharField(choices=[('GUARDIAN', 'Guardian'), ('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SOCIETY_MEMBER', 'Society Members'), ('SECURITY', 'Security Personnel'), ('VOLUNTEER', 'Community Volunteers'), ('ADMIN', 'System Admin'), ('COMMUNITY', 'Community (Society, Security, Volunteers)'), ('COMPLETED', 'Escalation Completed')], db_index=True, default='GUARDIAN', max_length=30),
        ),
    ]
