# Generated by Django 4.2.30 on 2026-08-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_emergencyincident_has_requested_backup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyincident',
            name='global_deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
