# Generated by Django 4.2.30 on 2026-08-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_location_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
